### ISSUE TITLE
'opened' event triggered so many times

### ISSUE THREAD

**Issue by v1p** [fanout/websockhop#7] opened 2015-11-25 14:20 UTC
the 'opened' event of wsh is triggered numerous times. i.e. handlePing & Pong are of no use apparently.
Is it normal behavior ?

Also, I may be not understanding it right. When the 'opened' event is triggered, am I supposed to 'subscribe' to a channel everytime ?

This is causing weird issues with Desktop notifications.

I am using wsh with pushpin.

Any help about what logs/debugging info is needed to get an eye on this is greatly appreciated.

**Comment by jkarneges** [comment] 2016-04-17 04:57
Hi @v1p, this one may have slipped through the cracks. The `opened` event will be triggered on each connect. Maybe we already talked about this in the Pushpin chatroom. Let me know if this is still an issue or not.

**Comment by jkarneges** [comment] 2016-05-27 08:28
Closing this, as we are likely talking about intended behavior. If there is really a bug, this issue can be reopened.

**Closed by jkarneges** 2016-05-27 08:28 UTC
